import type { Room } from './types'

export const ROOMS: Room[] = [
  {
    id: 0,
    name: 'Alpha',
    status: 'open',
    difficulty: 'easy',
    count: 4,
    players: [
      { initials: 'AK', type: 'filled' },
      { initials: 'RJ', type: 'filled' },
      { initials: 'MX', type: 'filled' },
      { initials: 'YOU', type: 'you' },
      { initials: '',   type: 'empty' },
      { initials: '',   type: 'empty' },
    ],
  },
  {
    id: 1,
    name: 'Beta',
    status: 'full',
    difficulty: 'medium',
    count: 6,
    players: [
      { initials: 'ZR', type: 'filled' },
      { initials: 'TK', type: 'filled' },
      { initials: 'OP', type: 'filled' },
      { initials: 'HN', type: 'filled' },
      { initials: 'WQ', type: 'filled' },
      { initials: 'LB', type: 'filled' },
    ],
  },
  {
    id: 2,
    name: 'Gamma',
    status: 'playing',
    difficulty: 'hard',
    count: 5,
    players: [
      { initials: 'CB',  type: 'filled' },
      { initials: 'VR',  type: 'filled' },
      { initials: 'NM',  type: 'filled' },
      { initials: 'YOU', type: 'you' },
      { initials: 'PX',  type: 'filled' },
      { initials: '',    type: 'empty' },
    ],
  },
  {
    id: 3,
    name: 'Delta',
    status: 'open',
    difficulty: 'easy',
    count: 1,
    players: [
      { initials: '',    type: 'empty' },
      { initials: '',    type: 'empty' },
      { initials: 'YOU', type: 'you' },
      { initials: '',    type: 'empty' },
      { initials: '',    type: 'empty' },
      { initials: '',    type: 'empty' },
    ],
  },
  {
    id: 4,
    name: 'Sigma',
    status: 'open',
    difficulty: 'medium',
    count: 1,
    players: [
      { initials: 'AR', type: 'filled' },
      { initials: '',   type: 'empty' },
      { initials: '',   type: 'empty' },
      { initials: '',   type: 'empty' },
      { initials: '',   type: 'empty' },
      { initials: '',   type: 'empty' },
    ],
  },
  {
    id: 5,
    name: 'Omega',
    status: 'open',
    difficulty: 'hard',
    count: 2,
    players: [
      { initials: 'KL',  type: 'filled' },
      { initials: 'ST',  type: 'filled' },
      { initials: '',    type: 'empty' },
      { initials: 'YOU', type: 'you' },
      { initials: '',    type: 'empty' },
      { initials: '',    type: 'empty' },
    ],
  },
]